# Generated by Django 3.1.5 on 2021-04-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_nutrition_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='profile_link',
        ),
    ]
