# Generated by Django 3.1.5 on 2021-04-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_favorite_profile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='is_private',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
