# Generated by Django 3.2 on 2021-04-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_workout_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpost',
            name='is_highlighted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
