# Generated by Django 3.1.5 on 2021-04-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_publicpost_is_inappropriate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicpost',
            name='is_inappropriate',
        ),
    ]
